config/routes.rb
Site::Application.routes.draw do

  get "tmdb/search"
  get "tmdb/getInfo"
  get "tmdb/getCoversByImdbId"

  resources :user_sessions do
    collection do
      get 'create_api'
    end
  end
  resources :users

  resources :catalogues do
    member do
		get 'changes'
		get 'grid'
    end
	resources :movies do
	end
    resources :apiv1 do
        collection do
            post 'update_many'
            get 'new_revisions'
        end
    end
  end

  root :to => "users#show"
  match "logout" => "user_sessions#destroy"
  match "login" => "user_sessions#new"

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end


end

app/models/catalogue.rb
class Catalogue < ActiveRecord::Base
  has_many :movies, :dependent => :destroy
  has_many :users
  has_many :revisions, :dependent => :nullify
  
  def all_movies
    return movies
  end
  
  def get_movies(page,limit,sidx,sord,name,year)
    offset = limit * (page -1)
     
    searched_movies = movies.where("active = ?",true)
    if name
		searched_movies = searched_movies.where("lower(name) LIKE ?",'%'+name.downcase+'%')
    end
    if year
		searched_movies = searched_movies.where("year = ?",year)
    end
    page_movies = searched_movies.limit(limit).offset(offset).order(sidx + " " + sord)
	count = searched_movies.count
     
    total_pages = (count.to_f/limit.to_f).ceil
    rows = Array.new(page_movies.length)
    page_movies.each_with_index { |m, i| rows[i] = {"id" => m.id, "cell" => [m.name,m.year,m.added.strftime("%b %d, %Y at %I:%M%p")] } }
         
    return {
		'records' => count,
		'page' => page,
		'total' => total_pages,
		'rows' => rows
    }
  end
  
  def get_revisions(page,limit,sidx,sord,type,movie,user)
	offset = limit * (page -1)
	search_revisions = revisions
	if type
		search_revisions = search_revisions.where("change_type = ?",type)
	end
	if movie
		search_revisions = search_revisions.joins(:movie).where("lower(movies.name) like ?",'%'+movie.downcase+'%')
	end
	if user
		search_revisions = search_revisions.joins(:user).where("lower(users.login) like ?",'%'+user.downcase+'%')
	end
	page_revisions = search_revisions.limit(limit).offset(offset).order(sidx + " " + sord).includes(:movie, :user)
	count = search_revisions.count
	
	total_pages = (count.to_f/limit.to_f).ceil
    rows = Array.new(page_revisions.length)
    page_revisions.each_with_index { |r, i| rows[i] = {"id" => r.id, "cell" => [r.change_type,r.movie.name,r.format_diff(:html),r.user.login,r.created_at.strftime("%b %d, %Y at %I:%M%p")] } }
    return {
		'records' => count,
		'page' => page,
		'total' => total_pages,
		'rows' => rows
    }
  end
  
  def create_revision(movie_holder, data)
    revision = revisions.build(:catalogue_id => self.id, :number => current_revision_number+1)
    movie = revision.movies.build(data)
    if(movie_holder == nil)
		movie_holder = movie.build_movie_holder(:catalogue_id => self.id)
	else
		movie.movie_holder = movie_holder
	end
	if !revision.save
	    return false
	end
	movie_holder.movie = movie
    if !movie_holder.save
		return false
	end
	return true
  end
  
  def new_revisions(number)
  
    return revisions.where(["id > ?", number])
  
  end
  
  def latest_revision
    return revisions.maximum("id")
  end
  
end

app/controllers/catalogues_controller.rb
class CataloguesController < ApplicationController
  before_filter :require_user
  #filter_access_to :all, :attribute_check => true
  # GET /catalogues
  # GET /catalogues.xml
  def index
    @catalogues = Catalogue.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @catalogues }
    end
  end

  # GET /catalogues/1
  # GET /catalogues/1.xml
  def show
    @catalogue = Catalogue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @catalogue }
    end
  end

  # GET /catalogues/new
  # GET /catalogues/new.xml
  def new
    @catalogue = Catalogue.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @catalogue }
    end
  end

  # GET /catalogues/1/edit
  def edit
    @catalogue = Catalogue.find(params[:id])
  end

  # POST /catalogues
  # POST /catalogues.xml
  def create
    @catalogue = Catalogue.new(params[:catalogue])

    respond_to do |format|
      if @catalogue.save
        format.html { redirect_to(@catalogue, :notice => 'Catalogue was successfully created.') }
        format.xml  { render :xml => @catalogue, :status => :created, :location => @catalogue }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @catalogue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /catalogues/1
  # PUT /catalogues/1.xml
  def update
    @catalogue = Catalogue.find(params[:id])

    respond_to do |format|
      if @catalogue.update_attributes(params[:catalogue])
        format.html { redirect_to(@catalogue, :notice => 'Catalogue was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @catalogue.errors, :status => :unprocessable_entity }
      end
    end
  end

  def grid
    @catalogue = Catalogue.find(params[:id])
	page = params[:page].to_i
	limit = params[:rows].to_i
	sidx = params[:sidx]
	sord = params[:sord]

	@movies = @catalogue.get_movies(page,limit,sidx,sord,params[:name],params[:year])

	respond_to do |format|
      format.json { render :json => @movies }
    end
  end

  # DELETE /catalogues/1
  # DELETE /catalogues/1.xml
  def destroy
    @catalogue = Catalogue.find(params[:id])
    @catalogue.destroy

    respond_to do |format|
      format.html { redirect_to(catalogues_url) }
      format.xml  { head :ok }
    end
  end

  def changes
	@catalogue = Catalogue.find(params[:id])

	respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @catalogue.get_revisions(params[:page].to_i,params[:rows].to_i,params[:sidx],params[:sord],params[:change_type],params["movies.name"],params["users.login"]) }
    end
  end

end

app/helpers/catalogues_helper.rb
module CataloguesHelper
end

app/views/catalogues/_form.html.erb
<%= form_for(@catalogue) do |f| %>
  <% if @catalogue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@catalogue.errors.count, "error") %> prohibited this catalogue from being saved:</h2>

      <ul>
      <% @catalogue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/catalogues/changes.html.erb
<% content_for :head do %>
<script type="text/javascript" src="/steal/steal.js?changes"></script>
<% end %>
<div id="changes-parent">
<table id="changes-table"></table>
<div id="changes-div"></div>
</div>

<div id="legend" style="text-align: center;">
	<span style="color:#580000;font-size:250%">■</span>
	Deleted
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<span style="color:#006600;font-size:250%">■</span>
	Added
</div>

app/views/catalogues/edit.html.erb
<h1>Editing catalogue</h1>

<%= render 'form' %>

<%= link_to 'Show', @catalogue %> |
<%= link_to 'Back', catalogues_path %>

app/views/catalogues/index.html.erb
<h1>Listing catalogues</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @catalogues.each do |catalogue| %>
  <tr>
    <td><%= link_to 'Show', catalogue %></td>
    <td><%= link_to 'Edit', edit_catalogue_path(catalogue) %></td>
    <td><%= link_to 'Destroy', catalogue, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Catalogue', new_catalogue_path %>

app/views/catalogues/new.html.erb
<h1>New catalogue</h1>

<%= render 'form' %>

<%= link_to 'Back', catalogues_path %>

app/views/catalogues/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_catalogue_path(@catalogue) %> |
<%= link_to 'Back', catalogues_path %>