config/routes.rb
Site::Application.routes.draw do

  get "tmdb/search"
  get "tmdb/getInfo"
  get "tmdb/getCoversByImdbId"

  resources :user_sessions do
    collection do
      get 'create_api'
    end
  end
  resources :users

  resources :catalogues do
    member do
		get 'changes'
		get 'grid'
    end
	resources :movies do
	end
    resources :apiv1 do
        collection do
            post 'update_many'
            get 'new_revisions'
        end
    end
  end

  root :to => "users#show"
  match "logout" => "user_sessions#destroy"
  match "login" => "user_sessions#new"

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end


end

app/models/user_session.rb
# app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # configuration here, see documentation for sub modules of Authlogic::Session
  params_key :api_key
  single_access_allowed_request_types :any
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create, :create_api]
  before_filter :require_user, :only => :destroy
  
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_back_or_default catalogue_movies_url(@user_session.record.catalogue)
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_user_session_url
  end
  
  def create_api
	@user_session = UserSession.new(params)
	respond_to do |format|
	    if @user_session.save
			user = @user_session.record
			format.json { render :json => { :api_key => user.single_access_token, :catalogue => user.catalogue_id, :permissions => user.role_symbols } }
	    else
	        format.json { render :json => { :error => 402 } }
	    end
    end
  end
  
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div style="position:relative; margin-left:5%;">
	<div style="position: relative; width:480px;height:360px;" class="ui-widget-shadow ui-corner-all"></div>
	<div style="position:absolute;top:20px;left:20px;width:400px;height:300px;padding:20px;" class="ui-widget ui-widget-content ui-corner-all">
	<h1>Login</h1>
	<% form_for :user_session, @user_session, :url => user_sessions_path do |f| %>
	  <% if @user_session.errors.any? %>
	  <div id="errorExplanation">
	    <h2>The following errors prohibited this form from being saved:</h2>
	    <ul>
	    <% @user_session.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	  <% end %>
	  <%= f.label :login %><br />
	  <%= f.text_field :login %><br />
	  <br />
	  <%= f.label :password %><br />
	  <%= f.password_field :password %><br />
	  <br />
	  <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
	  <br />
	  <%= f.submit "Login" %>
	<% end %>
	</div>
</div>